### ISSUE TITLE
Screen capture from SS_II.  Possible web page layout.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#1]
![ss_ii_screenshot](https://user-images.githubusercontent.com/39974784/42202009-e52ba9d4-7e4e-11e8-8644-3382d6282dd3.PNG)

**Comment by grumpyinca** [comment]
The column labeled "**fnx**" is used to activate fixes (**f**), min constraints (**n**) and max constraints (x).  The "**min**" and "**max**" columns are the upper & lower constraint values (cmin, cmax).  The "**Min?**" and "**Max?**" columns display the character string "**viol**" to draw the users attention to constraint violations.

**Comment by 1fifoto** [comment]
This is great, thank you. Now can you mock up a PCyl version?

**Comment by 1fifoto** [comment]
OK, so here is the first pass at trying to model the user interface and make is similar to what you have above. I have combined the min/max checkbox, min/max value and the min/max violation all into one cell.

![screen shot 2018-07-08 at 3 07 34 pm](https://user-images.githubusercontent.com/1581602/42423497-e8d3a5de-82c0-11e8-8566-1f0e2881dafa.png)

**Comment by 1fifoto** [comment]
Merged into master, closing
