### ISSUE TITLE
Handle floating point input and right justify numbers in input fields

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl-web#11]
Allow full floating point number with exponents such as "1.345e+5" as input. Also have the value right-justified in the input field '       1.345e+5'.

**Comment by 1fifoto** [comment]
Added "text-right" to className to right-justify input numbers. Can't close because doesn't accept scientific notation.

**Comment by grumpyinca** [comment]
Merged into master, and closing. Note: a separate issue is going to be written for floating-point (scientific notation) input.
