### ISSUE TITLE
Main Page title

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#15]
There are two things to communicate with version number in the title line (currently "Piston-Cylinder Design - Version 1.2"): the software release and the version of the design model (~format of the .DSN file). It may be necessary for future versions of the program to perform upgrades of older file formats. So, the text presented in the title line may want to be expanded to something like: "Piston-Cylinder Design - Software Release 0.2; Design Model Version 1.2".

Note:  The software release number and the design model version number may also appear as a Help : About menu item.

Note:  If pushed for vertical dimension page real estate, a responsive design might collapse out the page title.  See related point in issue #18.

**Comment by 1fifoto** [comment]
Mike, I've assigned this to you. Bri P.S. I have a way to extract the Git tag value and put it in a JS file that can then be accessed and displayed if you want.

**Comment by 1fifoto** [comment]
Integrating #21 "Create version.js generator script".

**Comment by 1fifoto** [comment]
Is this a little less "in your face" about the version?
![screen shot 2018-07-13 at 7 40 29 am](https://user-images.githubusercontent.com/1581602/42692110-1ed92c78-8670-11e8-8874-082b33076baa.png)

**Comment by grumpyinca** [comment]
Nicely done !  I favor putting this version info in the Help : About menu item.  The biggest reason is to reduce clutter to achieve a cleaner user interface.

**Comment by 1fifoto** [comment]
OK, then we'll leave this issue open until we have a Help.

**Comment by 1fifoto** [comment]
See #32 "Implement Help : About menu item", closing this in lieu of the other issue.
