### ISSUE TITLE
Adjust highlighting for violated constraints

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#16]
The red box used to highlight a violated constraint is more bold than necessary or desired. Just a few pixels wide should be sufficient. Also, if possible with reasonable effort, it would be desirable for violated constraint values to show in a different color, bold font or both.

**Comment by 1fifoto** [comment]
MIke, give this one a try. Bri

**Comment by grumpyinca** [comment]
Merged into master.  Closing.

**Comment by 1fifoto** [comment]
I'm making a change to this issue even though it is closed. In general I've come to realize that it's not good programming to use style=, but instead we should use classes: text-right. So changing from style={{color:cmin_color}} to className={cmin_class} where cmin_class is "text-right text-danger'. In other words, I reverted the change to be more similar to what what originally there.

**Comment by grumpyinca** [comment]
Merged to master.  Re-closing.
