### ISSUE TITLE
Main page: not-established constraint should get empty cell

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#17]
In an ideal world, constraints that are not established would have empty entry cells as opposed to zeros. In fact, the presence of a value in the cell could imply an active constraint and eliminate the need for that checkbox. The current situation requires the user to observe the state of the checkbox before interpreting the meaning of the zero entry. If the checkbox is overlooked, FORCE MIN 1000 could be interpreted as being in conflict with FORCE MAX 0.

**Comment by 1fifoto** [comment]
This has been done in issue 7 and released to master. Please review and close if you agree.

**Comment by 1fifoto** [comment]
Hmmm, I probably forgot to push it to Heroku. It is there now. Have a look:
![screen shot 2018-07-13 at 2 00 37 pm](https://user-images.githubusercontent.com/1581602/42709146-2b3c920e-86a5-11e8-8964-3fe1ffc0be68.png)

**Comment by grumpyinca** [comment]
See Slack chat session for conversation about checkboxes.  We may re-visit the issue in the future.  Closing.
