### ISSUE TITLE
Create "Objective Section" of the main web page

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#41]
This section of the main page is visualized as one (or a small number of) row(s) at or near the bottom.  A preference setting may be used to suppress the display of this section.  It is possible that display of this section would be tied to a preference setting that optionally suppresses the display of constraint violations.

This section should display:
 * objective function value
 * value of OBJMIN
 * Search termination criteria (OBJMIN, DELMIN, MAXIT, ShortSearch)
 * Iteration Count (ITNO) at Search completion
 * An indicator of "Strictly Feasible", "Marginally Feasible" or "Infeasible".  (see below)

A current version of the objective function value should be displayed any time  that the Objective Section is displayed.  The remainder of the listed information should clear from the page when the user changes any problem variable / quantity.  This subset of information should reappear at the conclusion of a search.  None of this information is required to be updated during the search computation process.

The Objective Section is a possible location for an indicator (spinner) showing search activity.

The Objective Section is not required to produce any text output (logging, etc.) for the Search function.

The indicator of "Strictly Feasible", "Marginally Feasible" or "Infeasible" does not have to be textual.  An icon or text style / color of the Objective Function value may be sufficient.  Check for a docs/design entry on the subject.

**Comment by 1fifoto** [comment]
Merged into master, closing. Note: I assume the spinner should be written as a separate issue.
