### ISSUE TITLE
Add violated_constraint_count into design model ?

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#42]
Currently, in equationsMiddleware.js the variable violated_constraint_count is used to help form the feasibility result string: "Not" or "Marginally" "Feasible".  

Should violated_constraint_count be added to the design model ?

Currently the string is stored:
store.dispatch(changeSearchResultsFeasibility(output));

Since the violated_constraint_count actually contains more information than the string, keeping it rather than the string it might be a better approach in the long run.

**Comment by 1fifoto** [comment]
Included as part of Issue 41, closing.
