### ISSUE TITLE
Provide demo mode alternative for failed startup fetch

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl-web#60]

**Comment by grumpyinca** [comment]
If some sort of database connection problem occurs, the user can be offered the opportunity to proceed in "demo" mode with the understanding that they will not be able to save their work.

It may also be possible to take this opportunity to provide suggestions for how to report or resolve the problem.

**Comment by 1fifoto** [comment]
Merged into master, closing
