### ISSUE TITLE
Provide activity indicator during DB fetch operation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#69]
While not a high priority, it would be nice to have some kind of activity indicator (progress bar, spinner, busy cursor, etc.) that shows during periods of database activity.  The current no-indicator situation creates a certain amount of ambiguity as to what is happening and whether or not the operation has already completed.

Implementation requirements are flexible.  For example, a pop-up with words to the effect of: "Database access in progress …" that automatically disappears when the operation is complete, should be a workable solution to this issue.

**Comment by 1fifoto** [comment]
Here is my spinner!
![pcyl](https://user-images.githubusercontent.com/1581602/43495242-80e492fa-94fc-11e8-9eb5-0219155bb591.gif)

**Comment by 1fifoto** [comment]
Merged into master, closing
