### ISSUE TITLE
Change PromptForDesign when no Server available

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl-web#91]
When the client starts and if the server is not available we pop-up an error modal message saying "GET of design names failed: Internal Server Error":
![screen shot 2018-08-03 at 6 27 26 pm](https://user-images.githubusercontent.com/1581602/43669750-f1397c6e-974a-11e8-8d84-5583bb01cf89.png)

The client should not put up this error nor should it pop-up the "Open Design Optimization : Platform ... Select design to open:" modal.
![screen shot 2018-08-03 at 6 28 57 pm](https://user-images.githubusercontent.com/1581602/43669788-4b9a311c-974b-11e8-8b4c-b07980305057.png)

Instead the client should pop-up the error modal message and load the initialState. The error message should say "GET of design names failed with message: \''+error.message+'\'. Using builtin initialState instead. You may continue in "demo mode" but you will be unable to save your work."

**Comment by grumpyinca** [comment]
Made multiple changes including modal header & body text.  Pushed to remote master.  Closing.
