### ISSUE TITLE
Possible for user to lose work on browser refresh.

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl-web#94]
In the process of testing PromptForDesign.js, I have realized that a simple browser refresh could cause a user to lose work … potentially lots of work.  We need to discuss.

**Comment by 1fifoto** [comment]
Welcome to the browser world. We could drop the React app and replace it with an NodeJS Express website. Is that what you are suggesting?

**Comment by grumpyinca** [comment]
Refer to discussion in [AutoSave feature](https://thegrumpys.github.io/pcyl-web/About/AutoSaveFeature)
